# Generated by Django 4.0.4 on 2022-10-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_google',
            field=models.BooleanField(default=False),
        ),
    ]
